version: "3"
services:
        nginx:
                image: nginx:latest
                container_name: nginx
                volumes:
                        - "./nginx.conf:/etc/nginx/conf.d/default.conf"
                        - "/home/nkdeepak/disk/certs:/etc/nginx/certs"
                ports:
                        - "80:80"
                        - "443:443"

                depends_on:
                        - "ksummary"
                networks:
                        - "kimo_nw"

        ksummary:
                build:
                        context: ./
                        dockerfile: Dockerfile
                image: summary:1.0.0
                ports:
                        - "8000:8000"
                volumes:
                        - "/home/nkdeepak/disk/models/bart-model:/home/user/model"
                        - "/home/nkdeepak/disk/models/bart-tokenizer:/home/user/tokenizer"
                environment:
                        - "MODEL_NAME=/home/user/model/"
                        - "TOKENIZER=/home/user/tokenizer"
                networks:
                        - "kimo_nw"
networks:
        kimo_nw:
                driver: bridge
